In [1]:
import numpy as np
import pandas as pd

In [2]:
# Q1. Pandas version

# What's the version of Pandas that you installed?
pd.__version__

'2.3.2'

In [3]:
# Getting the data
# For this homework, we'll use the Laptops Price dataset.
!curl -O https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 11  853k   11 96898    0     0    99k      0  0:00:08 --:--:--  0:00:08   99k
 29  853k   29  254k    0     0   126k      0  0:00:06  0:00:02  0:00:04  126k
 55  853k   55  472k    0     0   132k      0  0:00:06  0:00:03  0:00:03  132k
 64  853k   64  552k    0     0   138k      0  0:00:06  0:00:04  0:00:02  138k
 70  853k   70  600k    0     0   116k      0  0:00:07  0:00:05  0:00:02  116k
 72  853k   72  616k    0     0   102k      0  0:00:08  0:00:06  0:00:02  102k
 85  853k   85  728k    0     0  99151      0  0:00:08  0:00:07  0:00:01 88014
 90  853k   90  776k    0     0  97705      0  0:00:08  0:00:08 --:--:-- 68236
100  853k  100  853k    0     0    98k      0  0:00:08  0:00:08 --:--:-- 66300


In [4]:
# Now read it with Pandas.
df = pd.read_csv("car_fuel_efficiency.csv")
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [5]:
# Q2. Records count

# How many records are in the dataset?
len(df)

9704

In [6]:
# Q3. Fuel types

# How many fuel types are presented in the dataset?
df['fuel_type'].nunique()

2

In [7]:
# df.isnull().sum()

In [8]:
# Q4. Missing values

# How many columns in the dataset have missing values?
print((df.isnull().sum() != 0).sum())

4


In [9]:
# Q5. Max fuel efficiency

# What's the maximum fuel efficiency of cars from Asia?
print(np.round(df[df['origin'] == "Asia"]['fuel_efficiency_mpg'].max(), 2))

23.76


In [10]:
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

In [11]:
# Q6. Median value of horsepower

# Find the median value of horsepower column in the dataset.
med_hp = df['horsepower'].median()
med_hp

149.0

In [12]:
# Next, calculate the most frequent value of the same horsepower column.
mod_hp = df['horsepower'].mode().mean()
mod_hp

np.float64(152.0)

In [13]:
# Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
df['horsepower'] = df['horsepower'].fillna(mod_hp)

In [16]:
# Now, calculate the median value of horsepower once again.
new_med_hp = df["horsepower"].median()
print(new_med_hp)
# Has it changed?
print("No" if new_med_hp == med_hp else "Yes")
change = new_med_hp - med_hp
print("Yes, it increased" if change > 0 else "Yes, it decreased")

152.0
Yes
Yes, it increased


In [17]:
# Q7. Sum of weights

# Select all the cars from Asia
asian_car_df = df[df['origin'] == "Asia"]
# Select only columns vehicle_weight and model_year
asian_car_df = asian_car_df[["vehicle_weight", "model_year"]]
asian_car_df

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [19]:
# Select the first 7 values
svn_df = asian_car_df[:7]
svn_df

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [20]:
# Get the underlying NumPy array. Let's call it X.
X = svn_df.to_numpy()
X.shape, X

((7, 2),
 array([[2714.21930965, 2016.        ],
        [2783.86897424, 2010.        ],
        [3582.68736772, 2007.        ],
        [2231.8081416 , 2011.        ],
        [2659.43145076, 2016.        ],
        [2844.22753389, 2014.        ],
        [3761.99403819, 2019.        ]]))

In [21]:
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. 
# Let's call the result XTX.
XTX = X.T.dot(X)
XTX.shape, XTX

((2, 2),
 array([[62248334.33150762, 41431216.5073268 ],
        [41431216.5073268 , 28373339.        ]]))

In [23]:
# Compute the inverse of XTX.
iXTX = np.linalg.inv(XTX)
iXTX.shape, iXTX

((2, 2),
 array([[ 5.71497081e-07, -8.34509443e-07],
        [-8.34509443e-07,  1.25380877e-06]]))

In [25]:
# Create an array y with values [1100, 1300, 800, 900, 1000, 1100].
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y.shape, y

((7,), array([1100, 1300,  800,  900, 1000, 1100, 1200]))

In [26]:
# Multiply the inverse of XTX with the transpose of X, 
inv_trans_X = iXTX.dot(X.T)
inv_trans_X.shape, inv_trans_X

((2, 7),
 array([[-1.31202622e-04, -8.63909858e-05,  3.72634923e-04,
         -4.02726650e-04, -1.62513724e-04, -5.52342829e-05,
          4.65094049e-04],
        [ 2.62636846e-04,  1.96990690e-04, -4.73392228e-04,
          6.58944477e-04,  3.08357831e-04,  1.51636137e-04,
         -6.07979633e-04]]))

In [33]:
# and then multiply the result by y. Call the result w.
w = inv_trans_X.dot(y)
w.shape, w

((2,), array([0.01386421, 0.5049067 ]))

In [36]:
# What's the sum of all the elements of the result
sum_elem = np.round(w.sum(), 2)
sum_elem

np.float64(0.52)